// Generated by jmlspec from the .class file

package java.lang;

public class InterruptedException extends java.lang.Exception {

    /*@ public normal_behavior
      @   ensures standardThrowable(null);
      @*/
    //@ pure
    public InterruptedException();

    /*@ public normal_behavior
      @   ensures standardThrowable(s);
      @*/
    //@ pure
    public InterruptedException(/*@(houdini:parameter:constructor) non_null */ java.lang.String s);
}
